sudo: false
language: java

before_script:
  - psql -U postgres -c "create user test with password 'test';"
  - psql -U postgres -c "create database test owner test;"

script: mvn verify

matrix:
  include:
    - jdk: openjdk6
      addons:
        postgresql: "9.1"
    - jdk: oraclejdk8
      addons:
        postgresql: "9.1"
    - jdk: openjdk6
      addons:
        postgresql: "9.2"
    - jdk: oraclejdk8
      addons:
        postgresql: "9.2"
    - jdk: openjdk6
      addons:
        postgresql: "9.3"
    - jdk: oraclejdk8
      addons:
        postgresql: "9.3"
    - jdk: openjdk6
      addons:
        postgresql: "9.4"
    - jdk: oraclejdk8
      addons:
        postgresql: "9.4"
